var exposure_stimuli = [
  {
    "index": "1",
    "group": "no_shift",
    "item": "flower",
    "what_spec": "spec",
    "context_audio": "flower.wav",
    "continuum_step": "7",
    "stim_audio": "flower-2-2-7.wav",
    "continuation_audio": "flower1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "flower_good.jpeg",
    "comp_image": "flower_bad.jpeg"
  },
  {
    "index": "2",
    "group": "no_shift",
    "item": "flower",
    "what_spec": "spec",
    "context_audio": "flower.wav",
    "continuum_step": "15",
    "stim_audio": "flower-2-2-15.wav",
    "continuation_audio": "flower2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "flower_good.jpeg",
    "comp_image": "flower_bad.jpeg"
  },
  {
    "index": "3",
    "group": "no_shift",
    "item": "rabbit",
    "what_spec": "spec",
    "context_audio": "rabbit.wav",
    "continuum_step": "8",
    "stim_audio": "rabbit-2-3-8.wav",
    "continuation_audio": "rabbit1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "rabbit_good.jpeg",
    "comp_image": "rabbit_bad.jpeg"
  },
  {
    "index": "4",
    "group": "no_shift",
    "item": "rabbit",
    "what_spec": "spec",
    "context_audio": "rabbit.wav",
    "continuum_step": "16",
    "stim_audio": "rabbit-2-3-16.wav",
    "continuation_audio": "rabbit2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "rabbit_good.jpeg",
    "comp_image": "rabbit_bad.jpeg"
  },
  {
    "index": "5",
    "group": "no_shift",
    "item": "baseball",
    "what_spec": "spec",
    "context_audio": "baseball.wav",
    "continuum_step": "9",
    "stim_audio": "baseball-2-3-9.wav",
    "continuation_audio": "baseball1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "baseball_good.jpeg",
    "comp_image": "baseball_bad.jpeg"
  },
  {
    "index": "6",
    "group": "no_shift",
    "item": "baseball",
    "what_spec": "spec",
    "context_audio": "baseball.wav",
    "continuum_step": "15",
    "stim_audio": "baseball-2-3-15.wav",
    "continuation_audio": "baseball2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "baseball_good.jpeg",
    "comp_image": "baseball_bad.jpeg"
  },
  {
    "index": "7",
    "group": "no_shift",
    "item": "cake",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "10",
    "stim_audio": "cake-2-3-10.wav",
    "continuation_audio": "cake1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "cake_good.jpeg",
    "comp_image": "cake_bad.jpeg"
  },
  {
    "index": "8",
    "group": "no_shift",
    "item": "cake",
    "what_spec": "spec",
    "context_audio": "cake.wav",
    "continuum_step": "16",
    "stim_audio": "cake-2-3-16.wav",
    "continuation_audio": "cake2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "cake_good.jpeg",
    "comp_image": "cake_bad.jpeg"
  },
  {
    "index": "9",
    "group": "no_shift",
    "item": "waspsnest",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "10",
    "stim_audio": "waspsnest-2-3-10.wav",
    "continuation_audio": "waspsnest1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "waspsnest_good.jpeg",
    "comp_image": "waspsnest_bad.jpeg"
  },
  {
    "index": "10",
    "group": "no_shift",
    "item": "waspsnest",
    "what_spec": "spec",
    "context_audio": "waspsnest.wav",
    "continuum_step": "15",
    "stim_audio": "waspsnest-2-3-15.wav",
    "continuation_audio": "waspsnest2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "waspsnest_good.jpeg",
    "comp_image": "waspsnest_bad.jpeg"
  },
  {
    "index": "11",
    "group": "no_shift",
    "item": "cat",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "10",
    "stim_audio": "cat-2-3-10.wav",
    "continuation_audio": "cat1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "cat_good.jpeg",
    "comp_image": "cat_bad.jpeg"
  },
  {
    "index": "12",
    "group": "no_shift",
    "item": "cat",
    "what_spec": "spec",
    "context_audio": "cat.wav",
    "continuum_step": "16",
    "stim_audio": "cat-2-3-16.wav",
    "continuation_audio": "cat2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "cat_good.jpeg",
    "comp_image": "cat_bad.jpeg"
  },
  {
    "index": "13",
    "group": "no_shift",
    "item": "hedgehog",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "10",
    "stim_audio": "hedgehog-2-3-10.wav",
    "continuation_audio": "hedgehog1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "hedgehog_good.jpeg",
    "comp_image": "hedgehog_bad.jpeg"
  },
  {
    "index": "14",
    "group": "no_shift",
    "item": "hedgehog",
    "what_spec": "spec",
    "context_audio": "hedgehog.wav",
    "continuum_step": "15",
    "stim_audio": "hedgehog-2-3-15.wav",
    "continuation_audio": "hedgehog2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "hedgehog_good.jpeg",
    "comp_image": "hedgehog_bad.jpeg"
  },
  {
    "index": "15",
    "group": "no_shift",
    "item": "panda",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "11",
    "stim_audio": "panda-2-3-11.wav",
    "continuation_audio": "panda1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "panda_good.jpeg",
    "comp_image": "panda_bad.jpeg"
  },
  {
    "index": "16",
    "group": "no_shift",
    "item": "panda",
    "what_spec": "spec",
    "context_audio": "panda.wav",
    "continuum_step": "16",
    "stim_audio": "panda-2-3-16.wav",
    "continuation_audio": "panda2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "panda_good.jpeg",
    "comp_image": "panda_bad.jpeg"
  },
  {
    "index": "17",
    "group": "no_shift",
    "item": "cellphone",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "11",
    "stim_audio": "cellphone-2-3-11.wav",
    "continuation_audio": "cellphone1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "cellphone_good.jpeg",
    "comp_image": "cellphone_bad.jpeg"
  },
  {
    "index": "18",
    "group": "no_shift",
    "item": "cellphone",
    "what_spec": "spec",
    "context_audio": "cellphone.wav",
    "continuum_step": "15",
    "stim_audio": "cellphone-2-3-15.wav",
    "continuation_audio": "cellphone2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "cellphone_good.jpeg",
    "comp_image": "cellphone_bad.jpeg"
  },
  {
    "index": "19",
    "group": "no_shift",
    "item": "hammer",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "11",
    "stim_audio": "hammer-2-3-11.wav",
    "continuation_audio": "hammer1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "hammer_good.jpeg",
    "comp_image": "hammer_bad.jpeg"
  },
  {
    "index": "20",
    "group": "no_shift",
    "item": "hammer",
    "what_spec": "spec",
    "context_audio": "hammer.wav",
    "continuum_step": "16",
    "stim_audio": "hammer-2-3-16.wav",
    "continuation_audio": "hammer2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "hammer_good.jpeg",
    "comp_image": "hammer_bad.jpeg"
  },
  {
    "index": "21",
    "group": "no_shift",
    "item": "horse",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "11",
    "stim_audio": "horse-2-2-11.wav",
    "continuation_audio": "horse1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "horse_good.jpeg",
    "comp_image": "horse_bad.jpeg"
  },
  {
    "index": "22",
    "group": "no_shift",
    "item": "horse",
    "what_spec": "spec",
    "context_audio": "horse.wav.wav",
    "continuum_step": "15",
    "stim_audio": "horse-2-2-15.wav",
    "continuation_audio": "horse2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "horse_good.jpeg",
    "comp_image": "horse_bad.jpeg"
  },
  {
    "index": "23",
    "group": "no_shift",
    "item": "butterfly",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "12",
    "stim_audio": "butterfly-2-1-12.wav",
    "continuation_audio": "butterfly1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "butterfly_good.jpeg",
    "comp_image": "butterfly_bad.jpeg"
  },
  {
    "index": "24",
    "group": "no_shift",
    "item": "butterfly",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "16",
    "stim_audio": "butterfly-2-1-16.wav",
    "continuation_audio": "butterfly2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "butterfly_good.jpeg",
    "comp_image": "butterfly_bad.jpeg"
  },
  {
    "index": "25",
    "group": "no_shift",
    "item": "reindeer",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "12",
    "stim_audio": "reindeer-2-3-12.wav",
    "continuation_audio": "reindeer1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "reindeer_good.jpeg",
    "comp_image": "reindeer_bad.jpeg"
  },
  {
    "index": "26",
    "group": "no_shift",
    "item": "reindeer",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "15",
    "stim_audio": "reindeer-2-3-15.wav",
    "continuation_audio": "reindeer2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "reindeer_good.jpeg",
    "comp_image": "reindeer_bad.jpeg"
  },
  {
    "index": "27",
    "group": "no_shift",
    "item": "umbrella",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "12",
    "stim_audio": "umbrella-2-2-12.wav",
    "continuation_audio": "umbrella1_cont.wav",
    "affirmative_cont": "yes",
    "target_image": "umbrella_good.jpeg",
    "comp_image": "umbrella_bad.jpeg"
  },
  {
    "index": "28",
    "group": "no_shift",
    "item": "umbrella",
    "what_spec": "what",
    "context_audio": "whatsthis.wav",
    "continuum_step": "16",
    "stim_audio": "umbrella-2-2-16.wav",
    "continuation_audio": "umbrella2_cont.wav",
    "affirmative_cont": "no",
    "target_image": "umbrella_good.jpeg",
    "comp_image": "umbrella_bad.jpeg"
  }
]